import { Todo } from './model/todo.model';

export const TODO_DATA: Todo[] = [
  {
    id: 1,
    title: 'Task list and assignments',
    task_list: 1,
    created_by: '',
    priority: 1,
    completed: true,
    completed_date: '',
    created_date: '',
    updated_date: '',
  },
  {
    id: 2,
    title: 'Set due date and assignments',
    task_list: 1,
    created_by: '',
    priority: 2,
    completed: false,
    completed_date: '',
    created_date: '',
    updated_date: '',
  },
  {
    id: 3,
    title: 'Remove duplicate tasks and stories',
    task_list: 1,
    created_by: '',
    priority: 3,
    completed: true,
    completed_date: '',
    created_date: '',
    updated_date: '',
  },
  {
    id: 4,
    title: 'Update the user flow and stories',
    task_list: 1,
    created_by: '',
    priority: 4,
    completed: false,
    completed_date: '',
    created_date: '',
    updated_date: '',
  },
  {
    id: 5,
    title: 'Adjust the components',
    task_list: 1,
    created_by: '',
    priority: 5,
    completed: true,
    completed_date: '',
    created_date: '',
    updated_date: '',
  },
];
